### PR TITLE
Updated misc.py.

### PR DESCRIPTION
**Pull request by Jlobblet**
Added !bfl. Because what even is BFL?

### CODE REVIEW

**Comment by Jlobblet** [comment]
This is a shit idea btw.

**Comment by Jlobblet** [comment]
(error check failed to import discord.py)

**Comment by davidjrichardson** [comment]
"This is a shit idea btw" is a fantastic summary of this command

**Comment by Jlobblet** [comment]
I couldn't agree more.

**Comment by Jlobblet** [comment]
This is so sad, Apollo play !awoo

**Pull request closed without merging**
